# if env variable isn't set to undefined, otherwise surround in quotes
[[ -z "${BASE_CAMUNDA_URL}" ]] && BASE_CAMUNDA_URL=undefined || BASE_CAMUNDA_URL=\""${BASE_CAMUNDA_URL}"\"
[[ -z "${CAMUNDA_REST_PATH}" ]] && CAMUNDA_REST_PATH=undefined || CAMUNDA_REST_PATH=\""${CAMUNDA_REST_PATH}"\"
[[ -z "${CAMUNDA_SERVICE_PATH}" ]] && CAMUNDA_SERVICE_PATH=undefined || CAMUNDA_SERVICE_PATH=\""${CAMUNDA_SERVICE_PATH}"\"
[[ -z "${SPACE_ABSTRACTION_URL}" ]] && SPACE_ABSTRACTION_URL=undefined || SPACE_ABSTRACTION_URL=\""${SPACE_ABSTRACTION_URL}"\"
[[ -z "${BPMS_URL}" ]] && BPMS_URL=undefined || BPMS_URL=\""${BPMS_URL}"\"
[[ -z "${SMS_URL}" ]] && SMS_URL=undefined || SMS_URL=\""${SMS_URL}"\"
[[ -z "${DAL_URL}" ]] && DAL_URL=undefined || DAL_URL=\""${DAL_URL}"\"
[[ -z "${CSDMX_URL}" ]] && CSDMX_URL=undefined || CSDMX_URL=\""${CSDMX_URL}"\"
[[ -z "${USERS_URL}" ]] && USERS_URL=undefined || USERS_URL=\""${USERS_URL}"\"
[[ -z "${CAMUNDA_SCHEDULING_PROCESS_KEY}" ]] && CAMUNDA_SCHEDULING_PROCESS_KEY=undefined || CAMUNDA_SCHEDULING_PROCESS_KEY=\""${CAMUNDA_SCHEDULING_PROCESS_KEY}"\"


cat <<EOF
window.REACT_APP_BASE_CAMUNDA_URL=$BASE_CAMUNDA_URL;
window.REACT_APP_CAMUNDA_REST_PATH=$CAMUNDA_REST_PATH;
window.REACT_APP_CAMUNDA_SERVICE_PATH=$CAMUNDA_SERVICE_PATH;
window.REACT_APP_SPACE_ABSTRACTION_URL=$SPACE_ABSTRACTION_URL;
window.REACT_APP_BPMS_URL=$BPMS_URL;
window.REACT_APP_SMS_URL=$SMS_URL;
window.REACT_APP_DAL_URL=$DAL_URL;
window.REACT_APP_CSDMX_URL=$CSDMX_URL;
window.REACT_APP_USERS_URL=$USERS_URL;
window.REACT_APP_CAMUNDA_SCHEDULING_PROCESS_KEY=$CAMUNDA_SCHEDULING_PROCESS_KEY;
EOF